#!/usr/bin/env bash

# TODO: bash-it/{aliases,plugins}/enabled/ : These shall really be relative symlinks /me think.

# TODO: Import some BLFS functions (e.g. path manipulation)

# TODO: Source ~/.bashrc ?? At the end ? Here ?
# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
#[[ -f ~/.bashrc ]] && . ~/.bashrc

# TODO: Screen ?
# F.2012-11-03 Sat. : See http://geekscrap.com/2010/02/using-screen-as-your-login-shell/
#
#if [ "x`which screen 2> /dev/null`" != "x" -a ${SHLVL} -eq 1 ]; then
#    ((SHLVL+=1)); export SHLVL
#    #exec screen -R -e "^Ee" ${SHELL} -l
#    screen -R -e "^Ee" ${SHELL} -l
#    ((SHLVL-=1)); export SHLVL
#    echo
#    echo "///////////////////////////////////////////////////////"
#    echo "~/.bash_profile: End of screen-itized session, SHLVL=$SHLVL"
#    echo "///////////////////////////////////////////////////////"
#    echo
#fi

# TODO: List eventually existing screens ?
# F.2012-10-31 : List of screens.
#screen -ls

# F.2011-08-16
export LANG=en_US.UTF-8

# F.: See bash-it/lib/history.bash
#export HISTSIZE=1024
#export HISTFILESIZE=4096

# TODO: Personal custom stuff ?
# F.2011-08-16 : Source additional things.
#
#if [ -d ~/.bash_profile.d ]; then
#    for script in ~/.bash_profile.d/*.sh; do
#        [ -r "$script" ] && source "$script"
#    done
#fi

# TODO : Personal prompt stuff ? Make it a bash-it theme ?
# F.2011-08-16 : Prompt color, slightly modified from BLFS.
# Setup a red prompt for root and a green one for users.
#NORMAL="\[\e[0m\]"
#RED="\[\e[1;31m\]"
#GREEN="\[\e[1;32m\]"
#CYAN="\[\e[1;36m\]"
#YELLOW="\[\e[33;1m\]"
#WHITE="\[\e[37;1m\]"
#if [[ $EUID == 0 ]] ; then
#    USERATHOST=$RED
#else
#    USERATHOST=$GREEN
#fi
#PS1="$USERATHOST\u@\h $YELLOW\j $WHITE\w $USERATHOST\\$ $NORMAL"
#PS2="$USERATHOST> $NORMAL"

# Gentoo's PS1 : \[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\]

# Load RVM, if you are using it
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

# Add rvm gems and nginx to the path
#export PATH=$PATH:~/.gem/ruby/1.8/bin:/opt/nginx/sbin
[ -e ~/.gem/ruby/1.8/bin ] && pathprepend ~/.gem/ruby/1.8/bin

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='bobby'

# Your place for hosting Git repos. I use this for private repos.
#export GIT_HOSTING='git@git.domain.com'
export GIT_HOSTING='git@github.com:Oeil-de-nuit'

# Set my editor and git editor
#export EDITOR="/usr/bin/mate -w"
#export GIT_EDITOR='/usr/bin/mate -w'

# Set the path nginx
export NGINX_PATH='/opt/nginx'

# Don't check mail when opening terminal.
#unset MAILCHECK


# Change this to your console based IRC client of choice.

export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli

export TODO="t"

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

# F.2010-08-16 : Additional binary paths.
[ -d ~/bin       ] && pathprepend ~/bin
[ -d ~/tools/bin ] && pathprepend ~/tools/bin

# Print out some environment variables :
echo "Your environment, some of it :"
for e in HOSTNAME LANG LD_LIBRARY_PATH PATH DSQUERY SYBASE SYBASE_OCS; do
    echo "   $e = ${!e}"
done
